"""Clinical category for each of the model's 150 labels.

GENERATED FILE. Do not edit by hand -- edit ``docs/etiquetas_es_borrador.csv`` and rerun::

    python scripts/generate_label_categories.py

``docs/etiquetas_es_borrador.csv`` is the source of truth; see ``docs/etiquetas_es_borrador.md``
for how each label was assigned to a category. The category slugs are fixed and are never
translated or renamed: the app groups observations by them.
"""

from __future__ import annotations

DEFAULT_CATEGORY = "otro"

LABEL_CATEGORIES: dict[str, str] = {
    "ABNORMAL ECG": "resumen",
    "NORMAL SINUS RHYTHM": "ritmo",
    "NORMAL ECG": "resumen",
    "SINUS RHYTHM": "ritmo",
    "SINUS BRADYCARDIA": "ritmo",
    "ATRIAL FIBRILLATION": "ritmo",
    "SINUS TACHYCARDIA": "ritmo",
    "otherwise normal ecg": "resumen",
    "LEFT AXIS DEVIATION": "eje",
    "PREMATURE VENTRICULAR COMPLEXES": "ritmo",
    "BORDERLINE ECG": "resumen",
    "RIGHT BUNDLE BRANCH BLOCK": "conduccion",
    "SEPTAL INFARCT": "isquemia_infarto",
    "LEFT ATRIAL ENLARGEMENT": "hipertrofia",
    "NONSPECIFIC T WAVE ABNORMALITY": "repolarizacion",
    "LOW VOLTAGE QRS": "tecnico",
    "PREMATURE ATRIAL COMPLEXES": "ritmo",
    "ANTERIOR INFARCT": "isquemia_infarto",
    "INCOMPLETE RIGHT BUNDLE BRANCH BLOCK": "conduccion",
    "PREMATURE SUPRAVENTRICULAR COMPLEXES": "ritmo",
    "LEFT BUNDLE BRANCH BLOCK": "conduccion",
    "NONSPECIFIC T WAVE ABNORMALITY NOW EVIDENT IN": "repolarizacion",
    "NONSPECIFIC T WAVE ABNORMALITY NO LONGER EVIDENT IN": "repolarizacion",
    "T WAVE INVERSION NOW EVIDENT IN": "repolarizacion",
    "LATERAL INFARCT": "isquemia_infarto",
    "NONSPECIFIC ST ABNORMALITY": "repolarizacion",
    "LEFT VENTRICULAR HYPERTROPHY": "hipertrofia",
    "T WAVE INVERSION NO LONGER EVIDENT IN": "repolarizacion",
    "WITH RAPID VENTRICULAR RESPONSE": "ritmo",
    "QT HAS SHORTENED": "repolarizacion",
    "QT HAS LENGTHENED": "repolarizacion",
    "FUSION COMPLEXES": "ritmo",
    "ATRIAL FLUTTER": "ritmo",
    "MARKED SINUS BRADYCARDIA": "ritmo",
    "WITH SINUS ARRHYTHMIA": "ritmo",
    "NONSPECIFIC ST AND T WAVE ABNORMALITY": "repolarizacion",
    "LEFT ANTERIOR FASCICULAR BLOCK": "conduccion",
    "RIGHT AXIS DEVIATION": "eje",
    "ECTOPIC ATRIAL RHYTHM": "ritmo",
    "UNDETERMINED RHYTHM": "ritmo",
    "ANTEROSEPTAL INFARCT": "isquemia_infarto",
    "RIGHTWARD AXIS": "eje",
    "ST NOW DEPRESSED IN": "repolarizacion",
    "WITH SHORT PR": "conduccion",
    "WITH MARKED SINUS ARRHYTHMIA": "ritmo",
    "ST NO LONGER DEPRESSED IN": "repolarizacion",
    "INVERTED T WAVES HAVE REPLACED NONSPECIFIC T WAVE ABNORMALITY IN": "repolarizacion",
    "NON-SPECIFIC CHANGE IN ST SEGMENT IN": "repolarizacion",
    "NONSPECIFIC T WAVE ABNORMALITY HAS REPLACED INVERTED T WAVES IN": "repolarizacion",
    "JUNCTIONAL RHYTHM": "ritmo",
    "ELECTRONIC ATRIAL PACEMAKER": "marcapasos",
    "ABERRANT CONDUCTION": "conduccion",
    "ELECTRONIC VENTRICULAR PACEMAKER": "marcapasos",
    "T WAVE INVERSION LESS EVIDENT IN": "repolarizacion",
    "ANTEROLATERAL INFARCT": "isquemia_infarto",
    "WITH REPOLARIZATION ABNORMALITY": "repolarizacion",
    "RSR' OR QR PATTERN IN V1 SUGGESTS RIGHT VENTRICULAR CONDUCTION DELAY": "conduccion",
    "T WAVE INVERSION MORE EVIDENT IN": "repolarizacion",
    "WIDE QRS RHYTHM": "ritmo",
    "WITH PREMATURE VENTRICULAR OR ABERRANTLY CONDUCTED COMPLEXES": "ritmo",
    "RIGHT ATRIAL ENLARGEMENT": "hipertrofia",
    "INFERIOR INFARCT": "isquemia_infarto",
    "INCOMPLETE LEFT BUNDLE BRANCH BLOCK": "conduccion",
    "VOLTAGE CRITERIA FOR LEFT VENTRICULAR HYPERTROPHY": "hipertrofia",
    "OR DIGITALIS EFFECT": "repolarizacion",
    "BIFASCICULAR BLOCK": "conduccion",
    "ST NO LONGER ELEVATED IN": "repolarizacion",
    "WITH SLOW VENTRICULAR RESPONSE": "ritmo",
    "ST ELEVATION NOW PRESENT IN": "repolarizacion",
    "PREMATURE ECTOPIC COMPLEXES": "ritmo",
    "LEFT POSTERIOR FASCICULAR BLOCK": "conduccion",
    "T WAVE AMPLITUDE HAS DECREASED IN": "repolarizacion",
    "WITH A COMPETING JUNCTIONAL PACEMAKER": "ritmo",
    "RIGHT SUPERIOR AXIS DEVIATION": "eje",
    "BIATRIAL ENLARGEMENT": "hipertrofia",
    "VENTRICULAR-PACED RHYTHM": "marcapasos",
    "ATRIAL-PACED RHYTHM": "marcapasos",
    "T WAVE AMPLITUDE HAS INCREASED IN": "repolarizacion",
    "WITH QRS WIDENING": "conduccion",
    "WITH 1ST DEGREE AV BLOCK": "conduccion",
    "PROLONGED QT": "repolarizacion",
    "WITH PROLONGED AV CONDUCTION": "conduccion",
    "RIGHT VENTRICULAR HYPERTROPHY": "hipertrofia",
    "WITH QRS WIDENING AND REPOLARIZATION ABNORMALITY": "conduccion",
    "ATRIAL-SENSED VENTRICULAR-PACED RHYTHM": "marcapasos",
    "AV SEQUENTIAL OR DUAL CHAMBER ELECTRONIC PACEMAKER": "marcapasos",
    "PULMONARY DISEASE PATTERN": "otro",
    "ACUTE MI / STEMI": "isquemia_infarto",
    "INFERIOR-POSTERIOR INFARCT": "isquemia_infarto",
    "NONSPECIFIC INTRAVENTRICULAR CONDUCTION DELAY": "conduccion",
    "PREMATURE VENTRICULAR AND FUSION COMPLEXES": "ritmo",
    "IN A PATTERN OF BIGEMINY": "ritmo",
    "AV DUAL-PACED RHYTHM": "marcapasos",
    "SUPRAVENTRICULAR TACHYCARDIA": "ritmo",
    "VENTRICULAR-PACED COMPLEXES": "marcapasos",
    "WIDE QRS TACHYCARDIA": "ritmo",
    "RSR' PATTERN IN V1": "conduccion",
    "ST LESS DEPRESSED IN": "repolarizacion",
    "VENTRICULAR TACHYCARDIA": "ritmo",
    "EARLY REPOLARIZATION": "repolarizacion",
    "ST MORE DEPRESSED IN": "repolarizacion",
    "ANTEROLATERAL LEADS": "tecnico",
    "ELECTRONIC DEMAND PACING": "marcapasos",
    "RBBB AND LEFT ANTERIOR FASCICULAR BLOCK": "conduccion",
    "LATERAL INJURY PATTERN": "isquemia_infarto",
    "BIVENTRICULAR PACEMAKER DETECTED": "marcapasos",
    "SUSPECT UNSPECIFIED PACEMAKER FAILURE": "marcapasos",
    "WOLFF-PARKINSON-WHITE": "conduccion",
    "WITH VENTRICULAR ESCAPE COMPLEXES": "ritmo",
    "INFERIOR INJURY PATTERN": "isquemia_infarto",
    "CONSIDER RIGHT VENTRICULAR INVOLVEMENT IN ACUTE INFERIOR INFARCT": "isquemia_infarto",
    "ST ELEVATION HAS REPLACED ST DEPRESSION IN": "repolarizacion",
    "NONSPECIFIC INTRAVENTRICULAR BLOCK": "conduccion",
    "MASKED BY FASCICULAR BLOCK": "conduccion",
    "PEDIATRIC ECG ANALYSIS": "tecnico",
    "BLOCKED": "tecnico",
    "WITH UNDETERMINED RHYTHM IRREGULARITY": "ritmo",
    "LEFTWARD AXIS": "eje",
    "WITH 2ND DEGREE SA BLOCK MOBITZ I": "conduccion",
    "ACUTE": "tecnico",
    "ABNORMAL LEFT AXIS DEVIATION": "eje",
    "WITH COMPLETE HEART BLOCK": "conduccion",
    "NO P-WAVES FOUND": "ritmo",
    "ST LESS ELEVATED IN": "repolarizacion",
    "WITH RETROGRADE CONDUCTION": "conduccion",
    "ST MORE ELEVATED IN": "repolarizacion",
    "JUNCTIONAL BRADYCARDIA": "ritmo",
    "WITH VARIABLE AV BLOCK": "conduccion",
    "ANTERIOR INJURY PATTERN": "isquemia_infarto",
    "WITH JUNCTIONAL ESCAPE COMPLEXES": "ritmo",
    "ACUTE MI": "isquemia_infarto",
    "ACUTE PERICARDITIS": "otro",
    "POSTERIOR INFARCT": "isquemia_infarto",
    "IDIOVENTRICULAR RHYTHM": "ritmo",
    "WITH 2ND DEGREE SA BLOCK MOBITZ II": "conduccion",
    "R IN AVL": "tecnico",
    "SINUS/ATRIAL CAPTURE": "ritmo",
    "AV DUAL-PACED COMPLEXES": "marcapasos",
    "INFEROLATERAL INJURY PATTERN": "isquemia_infarto",
    "RBBB AND LEFT POSTERIOR FASCICULAR BLOCK": "conduccion",
    "ANTEROLATERAL INJURY PATTERN": "isquemia_infarto",
    "ATRIAL-PACED COMPLEXES": "marcapasos",
    "WITH SINUS PAUSE": "ritmo",
    "BIVENTRICULAR HYPERTROPHY": "hipertrofia",
    "ABNORMAL RIGHT AXIS DEVIATION": "eje",
    "SUPRAVENTRICULAR COMPLEXES": "ritmo",
    "WITH 2ND DEGREE AV BLOCK MOBITZ I": "conduccion",
    "WITH 2:1 AV CONDUCTION": "conduccion",
    "WITH AV DISSOCIATION": "conduccion",
    "MULTIFOCAL ATRIAL TACHYCARDIA": "ritmo",
}
